#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

mkdir -p dist/artifacts
tar cvzf dist/artifacts/docker-machine-driver-rancher.tar.gz bin/docker-machine-driver-rancher

echo Built dist/artifacts/docker-machine-driver-rancher.tar.gz
